attributes = [
    "KeyStringIdentifier",
    "KeyInt64Identifier",
    "Empty",
    "NumericIdentifier",
    "StringIdentifier",
    "POSIXTimestamp",
    "Int64",
    "Int64Identifier",
    "FloatLatitude",
    "FloatLongitude",
    "URI",
    "Count",
    "PositiveFloat",
    "Categorical",
    "Factor",
    "DateString",
    "FloatPrediction",
    "Regressor",
    "FreeText",
    "ISO8601Timestamp",
    "FromPostgresText",
    "FromPostgresBigInt",
    "FromPostgresCharacterVarying",
    "FromPostgresTimestampWithoutTimeZone",
    "FromPostgresInteger",
    "FromPostgresUuid",
    "FromPostgresName",
    "FromPostgresTimestampWithTimeZone",
    "FromPostgresChar",
    "FromPostgresBoolean",
    "FromPostgresJSONB",
    "FromPostgresArray",
    "FromPostgresUserDefined",
    "FromPostgresRegProc",
    "FromPostgresSmallInt",
    "FromPostgresReal",
    "FloatNumber",
    "FromPostgresDoublePrecision",
    "FromPostgresPgNodeTree",
    "FromPostgresPgLsn",
    "FromPostgresXid",
    "FromPostgresInterval",
    "FromPostgresAnyArray",
    "FromPostgresBytea",
    "FromPostgresRegType",
    "FromPostgresPgNDistinct",
    "FromPostgresPgDependencies",
    "FromPostgresInet",
    "FromPostgresNumeric",
    "FromPostgresOid",
    "NaturalNumber",
    "RegionName",
    "FIPSStateCode",
    "FIPSCountyCode",
    "IPEDSID",
    "USHigherEdName",
    "Proportion",
    "Year",
    "Month",
    "Week",
    "IntegerNumber",
    "CountryName",
    "WKTString",
    "VectorEmbedding",
    "CharacterPosition",
    "Boolean",
    "Float64",
    "FloatDensity",
    "FloatArea",
    "JSON",
]
